package sjmq

import "time"

type ItemUpdatedEvent struct {
	ID                   uint       `json:"id" mapstructure:"id"`
	CreatedAt            time.Time  `json:"created_at" mapstructure:"created_at"`
	UpdatedAt            time.Time  `json:"updated_at" mapstructure:"updated_at"`
	DeletedAt            *time.Time `json:"deleted_at" mapstructure:"deleted_at"`
	No                   string     `json:"no" mapstructure:"no"`
	LCatID               uint       `json:"l_cat_id" mapstructure:"l_cat_id"`
	MCatID               uint       `json:"m_cat_id" mapstructure:"m_cat_id"`
	SCatID               uint       `json:"s_cat_id" mapstructure:"s_cat_id"`
	SpecialCatID         string     `json:"special_cat_id" mapstructure:"special_cat_id"`
	TaxID                uint       `json:"tax_id" mapstructure:"tax_id"`
	BarNo                string     `json:"bar_no" mapstructure:"bar_no"`
	Name                 string     `json:"name" mapstructure:"name"`
	Spec                 string     `json:"spec" mapstructure:"spec"`
	Pwd                  string     `json:"pwd" mapstructure:"pwd"`
	UseIndex             string     `json:"use_index" mapstructure:"use_index"`
	Sku                  string     `json:"sku" mapstructure:"sku"`
	BonusID              uint       `json:"bonus_id" mapstructure:"bonus_id"`
	BarcodePrinted       bool       `json:"barcode_printed" mapstructure:"barcode_printed"`
	GiftAmount           float64    `json:"gift_amount" mapstructure:"gift_amount"`
	ProviderID           uint       `json:"provider_id" mapstructure:"provider_id"`
	OnHandInventory      float64    `json:"on_hand_inventory" mapstructure:"on_hand_inventory"`
	FirstQty             float64    `json:"first_qty" mapstructure:"first_qty"`
	FirstCost            float64    `json:"first_cost" mapstructure:"first_cost"`
	AverageCost          float64    `json:"average_cost" mapstructure:"average_cost"`
	WholesaleCost        float64    `json:"wholesale_cost" mapstructure:"wholesale_cost"`
	SecondCost           float64    `json:"second_cost" mapstructure:"second_cost"`
	UnitID               uint       `json:"unit_id" mapstructure:"unit_id"`
	PromotionNo          string     `json:"promotion_no" mapstructure:"promotion_no"`
	BasicQty             float64    `json:"basic_qty" mapstructure:"basic_qty"`
	ShipDate             time.Time  `json:"ship_date" mapstructure:"ship_date"`
	PurDate              time.Time  `json:"pur_date" mapstructure:"pur_date"`
	GiftPurQty           float64    `json:"gift_pur_qty" mapstructure:"gift_pur_qty"`
	LicenseCat           string     `json:"license_cat" mapstructure:"license_cat"`
	LicenseNo            string     `json:"license_no" mapstructure:"license_no"`
	DrugID               string     `json:"drug_id" mapstructure:"drug_id"`
	CtrlDrugID           string     `json:"ctrl_drug_id" mapstructure:"ctrl_drug_id"`
	ExpDate              time.Time  `json:"exp_date" mapstructure:"exp_date"`
	Pic                  string     `json:"pic" mapstructure:"pic"`
	Otcod1               string     `json:"otcod1" mapstructure:"otcod1"`
	Otcod2               string     `json:"otcod2" mapstructure:"otcod2"`
	Otcod3               string     `json:"otcod3" mapstructure:"otcod3"`
	Origin               string     `json:"origin" mapstructure:"origin"`
	Remark               string     `json:"remark" mapstructure:"remark"`
	Flag01               bool       `json:"flag01" mapstructure:"flag01"`
	Flag02               bool       `json:"flag02" mapstructure:"flag02"`
	Flag03               bool       `json:"flag03" mapstructure:"flag03"`
	Flag04               bool       `json:"flag04" mapstructure:"flag04"`
	Flag05               bool       `json:"flag05" mapstructure:"flag05"`
	Flag06               bool       `json:"flag06" mapstructure:"flag06"`
	Flag07               bool       `json:"flag07" mapstructure:"flag07"`
	Flag08               bool       `json:"flag08" mapstructure:"flag08"`
	Flag09               bool       `json:"flag09" mapstructure:"flag09"`
	Flag10               bool       `json:"flag10" mapstructure:"flag10"`
	Flag11               bool       `json:"flag11" mapstructure:"flag11"`
	Flag12               bool       `json:"flag12" mapstructure:"flag12"`
	Flag13               bool       `json:"flag13" mapstructure:"flag13"`
	Flag14               bool       `json:"flag14" mapstructure:"flag14"`
	Flag15               bool       `json:"flag15" mapstructure:"flag15"`
	Flag16               bool       `json:"flag16" mapstructure:"flag16"`
	DynamicOrderStandard string     `json:"dynamic_order_standard" mapstructure:"dynamic_order_standard"`
	DynamicOrderYears    string     `json:"dynamic_order_years" mapstructure:"dynamic_order_years"`
	DynamicOrderRate     string     `json:"dynamic_order_rate" mapstructure:"dynamic_order_rate"`
	DeliveryMethod       string     `json:"delivery_method" mapstructure:"delivery_method"`
	PosProperty          string     `json:"pos_property" mapstructure:"pos_property"`
	HqChange             string     `json:"hq_change" mapstructure:"hq_change"`
	ItemProperty         string     `json:"item_property" mapstructure:"item_property"`
	DrugProperty         string     `json:"drug_property" mapstructure:"drug_property"`
	Turnover             float64    `json:"turnover" mapstructure:"turnover"`
	FranchiseFee         float64    `json:"franchise_fee" mapstructure:"franchise_fee"`
	Used                 bool       `json:"used" mapstructure:"used"`
	CreatedBy            string     `json:"created_by" mapstructure:"created_by"`
	UpdatedBy            string     `json:"updated_by" mapstructure:"updated_by"`
}
